package com.delivery.fdp.service;

import com.delivery.fdp.config.RuntimeProperties;
import com.delivery.fdp.model.PocProject;
import com.delivery.fdp.repository.DeploymentRepository;
import com.delivery.fdp.repository.PocProjectRepository;
import org.springframework.stereotype.Service;
import org.springframework.util.StringUtils;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.Map;

@Service
public class DeploymentService {
    private final RuntimeProperties props; private final PocProjectRepository projects; private final DeploymentRepository deployments; private final CommandExecutor exec;
    public DeploymentService(RuntimeProperties p,PocProjectRepository pr,DeploymentRepository dr,CommandExecutor e){props=p;projects=pr;deployments=dr;exec=e;}
    public long deploy(Long projectId){PocProject p=project(projectId);long task=deployments.createTask(projectId);try{Path ws=workspace(p);Files.createDirectories(ws);step(task,"GIT_SYNC");String git=Files.exists(ws.resolve(".git"))?"git fetch --prune origin && git checkout "+q(p.getGitBranch())+" && git reset --hard origin/"+q(p.getGitBranch()):"git clone --branch "+q(p.getGitBranch())+" --single-branch "+q(p.getGitUrl())+" .";run(task,git,ws,Map.of());String commit=props.isExecutionEnabled()?run(task,"git rev-parse HEAD",ws,Map.of()).trim():"DRY-RUN";deployments.commit(task,commit);if(StringUtils.hasText(p.getBuildCommand())){step(task,"BUILD");run(task,p.getBuildCommand(),ws,Map.of());}if("STATIC".equals(p.getProjectType()))publishStatic(task,p,ws);else startNode(task,p,ws);projects.updateDeployment(projectId,"STATIC".equals(p.getProjectType())?"PUBLISHED":"RUNNING",commit);step(task,"ROUTE");regenerateNginx(task);deployments.finish(task,"SUCCESS");return task;}catch(Exception e){projects.updateStatus(projectId,"FAILED");deployments.finish(task,"FAILED");deployments.log(task,e.getMessage());return task;}}
    public void restart(Long id){PocProject p=node(id);check(runRaw("pm2 restart "+q(p.getPm2Name()),workspace(p)));projects.updateStatus(id,"RUNNING");regenerateNginx(null);}
    public void stop(Long id){PocProject p=node(id);check(runRaw("pm2 stop "+q(p.getPm2Name()),workspace(p)));projects.updateStatus(id,"STOPPED");regenerateNginx(null);}
    private void publishStatic(long task,PocProject p,Path ws)throws Exception{step(task,"PUBLISH_STATIC");Path src=ws.resolve(p.getBuildOutput()).normalize();if(!src.startsWith(ws))throw new IllegalArgumentException("Invalid buildOutput");Path root=Path.of(props.getStaticRoot()).toAbsolutePath().normalize();Path dest=root.resolve(p.getPreviewPath().replaceFirst("^/","")).normalize();if(!dest.startsWith(root))throw new IllegalArgumentException("Invalid previewPath");Files.createDirectories(dest);run(task,"rsync -a --delete --exclude=.git --exclude=node_modules "+q(src+"/")+" "+q(dest+"/"),ws,Map.of());}
    private void startNode(long task,PocProject p,Path ws)throws Exception{step(task,"START_NODE");Path root=Path.of(props.getDataRoot()).toAbsolutePath().normalize();Path dir=root.resolve(p.getProjectCode()).normalize();if(!dir.startsWith(root))throw new IllegalArgumentException("Invalid data path");Files.createDirectories(dir);Path db=dir.resolve(p.getSqlitePath()).normalize();if(!db.startsWith(dir))throw new IllegalArgumentException("Invalid sqlitePath");Map<String,String> env=new HashMap<>();env.put("PORT",String.valueOf(p.getInternalPort()));env.put("SQLITE_PATH",db.toString());run(task,"pm2 delete "+q(p.getPm2Name())+" >/dev/null 2>&1 || true; pm2 start bash --name "+q(p.getPm2Name())+" -- -lc "+q(p.getStartCommand()),ws,env);run(task,"pm2 save",ws,env);}
    private void regenerateNginx(Long task){try{StringBuilder c=new StringBuilder("# Generated by FDP. Do not edit manually.\nserver {\n    listen "+props.getNginxPublicPort()+";\n    server_name _;\n\n");Path staticRoot=Path.of(props.getStaticRoot()).toAbsolutePath().normalize();for(PocProject p:projects.findPublished()){if("STATIC".equals(p.getProjectType()))c.append("    location ^~ ").append(p.getPreviewPath()).append("/ {\n        root ").append(staticRoot.toString().replace("\\","/")).append(";\n        try_files $uri $uri/ ").append(p.getPreviewPath()).append("/index.html;\n    }\n\n");else c.append("    location ^~ ").append(p.getPreviewPath()).append("/ {\n        proxy_pass http://127.0.0.1:").append(p.getInternalPort()).append("/;\n        proxy_http_version 1.1;\n        proxy_set_header Host $host;\n        proxy_set_header X-Real-IP $remote_addr;\n        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n    }\n\n");}c.append("}\n");Path file=Path.of(props.getNginxConfigFile()).toAbsolutePath().normalize();if(file.getParent()!=null)Files.createDirectories(file.getParent());Files.writeString(file,c.toString());CommandExecutor.Result r=exec.execute(props.getNginxReloadCommand(),file.getParent());if(task!=null)deployments.log(task,r.output());check(r);}catch(Exception e){throw new IllegalStateException("Nginx configuration failed: "+e.getMessage(),e);}}
    private Path workspace(PocProject p){Path root=Path.of(props.getWorkspaceRoot()).toAbsolutePath().normalize();Path ws=root.resolve(p.getProjectCode()).normalize();if(!ws.startsWith(root))throw new IllegalArgumentException("Invalid workspace");return ws;}
    private PocProject project(Long id){return projects.findById(id).orElseThrow(()->new IllegalArgumentException("POC project not found: "+id));}
    private PocProject node(Long id){PocProject p=project(id);if(!"NODE_SQLITE".equals(p.getProjectType()))throw new IllegalArgumentException("Only NODE_SQLITE has a process");return p;}
    private void step(long t,String s){deployments.step(t,s);deployments.log(t,"["+s+"]");}
    private String run(long t,String cmd,Path cwd,Map<String,String> env){CommandExecutor.Result r=exec.execute(cmd,cwd,env);deployments.log(t,"$ "+cmd+"\n"+r.output());check(r);return r.output();}
    private CommandExecutor.Result runRaw(String cmd,Path cwd){return exec.execute(cmd,cwd);}
    private void check(CommandExecutor.Result r){if(!r.success())throw new IllegalStateException("Command failed ("+r.exitCode()+"): "+r.output());}
    private String q(Object v){String s=String.valueOf(v);if(!s.matches("^[A-Za-z0-9_./:@\\ -]+$"))throw new IllegalArgumentException("Unsafe command argument");return "'"+s.replace("'","'\\''")+"'";}
}
