import axios from 'axios'

const http=axios.create({baseURL:'/api'})

export const listProjects=()=>http.get('/poc-projects').then(r=>r.data)
export const createProject=data=>http.post('/poc-projects',data).then(r=>r.data)
export const updateProject=(id,data)=>http.put(`/poc-projects/${id}`,data).then(r=>r.data)
export const deleteProject=id=>http.delete(`/poc-projects/${id}`)
export const getDeploymentPlan=id=>http.get(`/poc-projects/${id}/deployment-plan`).then(r=>r.data)
export const deployProject=id=>http.post(`/poc-projects/${id}/deploy`).then(r=>r.data)
export const syncProjectSource=id=>http.post(`/poc-projects/${id}/sync-source`).then(r=>r.data)
export const listStaticEntries=id=>http.get(`/poc-projects/${id}/static-entries`).then(r=>r.data)
export const restartProject=id=>http.post(`/poc-projects/${id}/restart`).then(r=>r.data)
export const stopProject=id=>http.post(`/poc-projects/${id}/stop`).then(r=>r.data)
export const getRuntimeLogs=id=>http.get(`/poc-projects/${id}/runtime-logs`).then(r=>r.data.content)
export const getRuntimeStatus=()=>http.get('/runtime').then(r=>r.data)
export const listDeployments=projectId=>http.get('/deployments',{params:projectId?{projectId}:{}}).then(r=>r.data)
export const getDeploymentSteps=id=>http.get(`/deployments/${id}/steps`).then(r=>r.data)
export const getDeploymentLogs=id=>http.get(`/deployments/${id}/logs`).then(r=>r.data)

export const getStaticCatalog=()=>http.get('/static-catalog').then(r=>r.data)
export const refreshStaticCatalog=()=>http.post('/static-catalog/refresh').then(r=>r.data)
export const activateStaticProject=projectName=>http.post('/static-catalog/activate',{projectName}).then(r=>r.data)

export const getYunxiaoStatus=()=>http.get('/yunxiao/status').then(r=>r.data)
export const listYunxiaoPipelines=params=>http.get('/yunxiao/pipelines',{params}).then(r=>r.data)
export const listYunxiaoPipelineRuns=(pipelineId,params)=>http.get(`/yunxiao/pipelines/${pipelineId}/runs`,{params}).then(r=>r.data)
export const getYunxiaoPipelineRun=(pipelineId,runId)=>http.get(`/yunxiao/pipelines/${pipelineId}/runs/${runId}`).then(r=>r.data)
export const listYunxiaoRepositories=params=>http.get('/yunxiao/packages/repositories',{params}).then(r=>r.data)
export const listYunxiaoArtifacts=(repoId,params)=>http.get(`/yunxiao/packages/repositories/${repoId}/artifacts`,{params}).then(r=>r.data)

export const listSourceCredentials=()=>http.get('/source-credentials').then(r=>r.data)
export const createSourceCredential=data=>http.post('/source-credentials',data).then(r=>r.data)
export const updateSourceCredential=(id,data)=>http.put(`/source-credentials/${id}`,data).then(r=>r.data)
export const deleteSourceCredential=id=>http.delete(`/source-credentials/${id}`)
export const testSourceCredential=(id,data)=>http.post(`/source-credentials/${id}/test`,data).then(r=>r.data)
