server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: financial-delivery-platform
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:fdp}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver

fdp:
  runtime:
    execution-enabled: ${FDP_EXECUTION_ENABLED:false}
    workspace-root: ${FDP_WORKSPACE_ROOT:./runtime/workspaces}
    static-root: ${FDP_STATIC_ROOT:./runtime/sites}
    data-root: ${FDP_DATA_ROOT:./runtime/data}
    nginx-config-file: ${FDP_NGINX_CONFIG_FILE:./runtime/nginx/fdp-poc.conf}
    nginx-public-port: ${FDP_PUBLIC_PORT:8090}
    nginx-reload-command: ${FDP_NGINX_RELOAD_COMMAND:nginx -t && nginx -s reload}
