<script setup>
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { ArrowLeft, Database, PackageCheck, Plus, Save, Server, Settings2, Trash2 } from 'lucide-vue-next'
import PageHeader from '../components/PageHeader.vue'
import { createManagedProject, getManagedRuntimeImages } from '../api'

const emit=defineEmits(['navigate'])
const DRAFT_KEY='fdp-managed-project-draft'
const PICK_TARGET_KEY='fdp-artifact-selection-target'
const saving=ref(false),loading=ref(true),error=ref(''),images=ref([])
const form=reactive({projectName:'',databaseName:'',runtimeImage:'',workDirectory:'.',serviceMode:'DIRECT',servicePort:8080,nginxStaticDirectory:'frontend/dist',nginxApiPrefix:'/api/',nginxBackendPort:8080,envContent:'',artifacts:[]})
const hasArtifacts=computed(()=>form.artifacts.length>0)
function err(e){return e.response?.data?.message||e.message||'操作失败'}
function readDraft(){try{const value=JSON.parse(sessionStorage.getItem(DRAFT_KEY)||'{}');if(value&&typeof value==='object'){for(const key of ['projectName','databaseName','runtimeImage','workDirectory','serviceMode','servicePort','nginxStaticDirectory','nginxApiPrefix','nginxBackendPort','envContent'])if(value[key]!==undefined&&value[key]!==null)form[key]=value[key];form.artifacts=Array.isArray(value.artifacts)?value.artifacts.map((a,i)=>({repositoryId:String(a.repositoryId||a.repoId||''),repositoryName:a.repositoryName||a.repoName||'',artifactName:a.artifactName||'',latestVersion:a.latestVersion||'',targetDirectory:a.targetDirectory||'.',sortOrder:i})).filter(a=>a.repositoryId&&a.artifactName):[]}}catch{}}
function persistDraft(){sessionStorage.setItem(DRAFT_KEY,JSON.stringify({projectName:form.projectName,databaseName:form.databaseName,runtimeImage:form.runtimeImage,workDirectory:form.workDirectory,serviceMode:form.serviceMode,servicePort:form.servicePort,nginxStaticDirectory:form.nginxStaticDirectory,nginxApiPrefix:form.nginxApiPrefix,nginxBackendPort:form.nginxBackendPort,envContent:form.envContent,artifacts:form.artifacts}))}
function chooseArtifacts(){persistDraft();sessionStorage.setItem(PICK_TARGET_KEY,JSON.stringify({mode:'create',createdAt:Date.now()}));emit('navigate','/artifacts')}
function removeArtifact(index){form.artifacts.splice(index,1)}
function cancel(){sessionStorage.removeItem(DRAFT_KEY);sessionStorage.removeItem(PICK_TARGET_KEY);emit('navigate','/containers')}
async function save(){saving.value=true;error.value='';try{if(!form.projectName.trim())throw new Error('请填写项目名称');if(!form.databaseName.trim())throw new Error('请填写 Database 名称');if(!form.runtimeImage)throw new Error('请选择 Runtime Image');if(!form.artifacts.length)throw new Error('请先从制品仓库选择至少一个制品');const payload={projectName:form.projectName.trim(),databaseName:form.databaseName.trim(),runtimeImage:form.runtimeImage,workDirectory:form.workDirectory||'.',startCommand:'',serviceMode:form.serviceMode,servicePort:Number(form.servicePort),nginxStaticDirectory:form.serviceMode==='NGINX'?form.nginxStaticDirectory:null,nginxApiPrefix:form.serviceMode==='NGINX'?form.nginxApiPrefix:'/api/',nginxBackendPort:form.serviceMode==='NGINX'?Number(form.nginxBackendPort):null,envContent:form.envContent,artifacts:form.artifacts.map((a,i)=>({repositoryId:a.repositoryId,repositoryName:a.repositoryName,artifactName:a.artifactName,targetDirectory:a.targetDirectory||'.',sortOrder:i}))};const created=await createManagedProject(payload);sessionStorage.removeItem(DRAFT_KEY);sessionStorage.removeItem(PICK_TARGET_KEY);sessionStorage.setItem('fdp-managed-project-flash','项目已创建。现在可以继续维护制品绑定和运行配置。');emit('navigate',`/containers/${created.id}/edit`)}catch(e){error.value=err(e)}finally{saving.value=false}}
watch(form,persistDraft,{deep:true})
onMounted(async()=>{readDraft();sessionStorage.removeItem(PICK_TARGET_KEY);try{images.value=await getManagedRuntimeImages();if(!form.runtimeImage)form.runtimeImage=images.value[0]||''}catch(e){error.value=err(e)}finally{loading.value=false}})
</script>

<template><div class="page-stack restructure-page">
<PageHeader title="新建项目" description="创建项目运行空间并绑定 Packages 制品。制品会作为项目的持久绑定保存；启动命令在创建后进入编辑项目填写。"><template #actions><button class="soft-button" @click="cancel"><ArrowLeft :size="14"/>返回项目部署</button></template></PageHeader>
<div v-if="error" class="error-banner">{{error}}</div><div v-if="loading" class="panel empty-state">正在读取运行环境…</div>
<template v-else>
<section class="panel project-create-form"><div class="panel-head"><div><h2><Database :size="18"/>1. 项目基础配置</h2><p>一个项目固定绑定一个 database；项目名称全局唯一。</p></div></div><div class="form-grid restructure-form-grid"><label>项目名称 *<input v-model="form.projectName" placeholder="financial-system"/></label><label>Database *<input v-model="form.databaseName" placeholder="financial_system"/><small>创建后不可切换到其他 database。</small></label><label>Runtime Image *<select v-model="form.runtimeImage"><option value="">请选择</option><option v-for="image in images" :key="image" :value="image">{{image}}</option></select></label><label>工作目录<input v-model="form.workDirectory" placeholder="."/><small><code>.</code> 表示 current/，创建后可以结合真实解压目录继续调整。</small></label></div></section>
<section class="panel project-create-form"><div class="panel-head"><div><h2><PackageCheck :size="18"/>2. 项目制品</h2><p>制品会持久绑定到项目。这里只配置来源和解压位置，具体版本在部署时选择。</p></div><button class="soft-button" @click="chooseArtifacts"><Plus :size="14"/>从制品仓库{{hasArtifacts?'继续选择':'选择制品'}}</button></div><div v-if="!hasArtifacts" class="empty-state">当前还没有绑定制品。<button class="link-button" @click="chooseArtifacts">前往制品仓库选择</button></div><div v-else style="padding:14px 16px;display:flex;flex-direction:column;gap:10px"><article v-for="(artifact,index) in form.artifacts" :key="`${artifact.repositoryId}-${artifact.artifactName}`" style="border:1px solid #e5e7eb;border-radius:8px;padding:14px;display:grid;grid-template-columns:minmax(220px,1.5fr) minmax(180px,1fr) 160px 36px;gap:12px;align-items:end"><div><div style="font-size:10px;color:#94a3b8">Packages 制品</div><strong style="display:block;margin-top:5px">{{artifact.artifactName}}</strong><small class="cell-note">{{artifact.repositoryName||artifact.repositoryId}} · {{artifact.repositoryId}}</small></div><div><div style="font-size:10px;color:#94a3b8">版本</div><strong style="display:block;margin-top:5px">部署时选择</strong><small class="cell-note">当前最新：{{artifact.latestVersion||'-'}}</small></div><label>解压目录<input v-model="artifact.targetDirectory" placeholder="."/><small>相对 current/</small></label><button class="icon-button danger" title="移除" @click="removeArtifact(index)"><Trash2 :size="14"/></button></article></div></section>
<section class="panel project-create-form"><div class="panel-head"><div><h2><Server :size="18"/>3. 服务配置</h2><p>这里只确定 Container 如何提供项目服务；启动命令在创建后的编辑页配置。</p></div></div><div class="form-grid restructure-form-grid"><label>服务模式<select v-model="form.serviceMode"><option value="DIRECT">DIRECT · 应用直接服务</option><option value="NGINX">NGINX · 前端 + API 合并</option></select></label><label>项目服务端口<input v-model="form.servicePort" type="number" min="1" max="65535"/></label><template v-if="form.serviceMode==='NGINX'"><label>静态目录<input v-model="form.nginxStaticDirectory" placeholder="frontend/dist"/></label><label>API 前缀<input v-model="form.nginxApiPrefix" placeholder="/api/"/></label><label>后端端口<input v-model="form.nginxBackendPort" type="number" min="1" max="65535"/></label></template></div><div class="inline-note" style="margin:0 20px 20px"><Settings2 :size="15"/>创建成功后会直接进入“编辑项目”，在那里查看 current/ 目录并填写启动命令。</div></section>
<section class="panel project-create-form"><div class="panel-head"><div><h2><Settings2 :size="18"/>4. 环境变量</h2><p>这里只填写项目自定义变量；数据库连接变量由 FDP 自动提供。</p></div></div><label style="display:flex;flex-direction:column;gap:7px;padding:18px 20px">环境变量（每行 KEY=VALUE）<textarea v-model="form.envContent" rows="7" spellcheck="false" placeholder="SPRING_PROFILES_ACTIVE=prod" style="width:100%;resize:vertical;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;line-height:1.55"></textarea><small>FDP 自动提供 DB_HOST / DB_PORT / DB_NAME / DB_USER / DB_PASSWORD。</small></label></section>
<section class="panel project-create-footer"><button class="soft-button" @click="cancel">取消</button><button class="primary-button" :disabled="saving||!hasArtifacts" @click="save"><Save :size="14"/>{{saving?'创建中…':'创建项目'}}</button></section>
</template></div></template>
