<script setup>
import { onMounted, reactive, ref } from 'vue'
import { Play, Plus, RefreshCw, RotateCcw, Save, Square } from 'lucide-vue-next'
import PageHeader from '../components/PageHeader.vue'
import {createManagedProject,getManagedRuntimeImages,listManagedProjects,previewManagedProject,restartManagedProject,startManagedProject,stopManagedProject} from '../api'

const projects=ref([]),images=ref([]),loading=ref(false),saving=ref(false),error=ref(''),info=ref(''),showCreate=ref(false)
const form=reactive({projectName:'',databaseName:'',runtimeImage:'',workDirectory:'.',startCommand:'java -jar app.jar',serviceMode:'DIRECT',servicePort:8080,nginxStaticDirectory:'frontend/dist',nginxApiPrefix:'/api/',nginxBackendPort:8080,envContent:'',artifacts:[{repositoryId:'',repositoryName:'',artifactName:'',targetDirectory:'.',sortOrder:0}]})
function err(e){return e.response?.data?.message||e.message||'操作失败'}
function addArtifact(){form.artifacts.push({repositoryId:'',repositoryName:'',artifactName:'',targetDirectory:'.',sortOrder:form.artifacts.length})}
async function load(){loading.value=true;error.value='';try{[projects.value,images.value]=await Promise.all([listManagedProjects(),getManagedRuntimeImages()]);if(!form.runtimeImage)form.runtimeImage=images.value[0]||''}catch(e){error.value=err(e)}finally{loading.value=false}}
async function save(){saving.value=true;error.value='';try{await createManagedProject({...form,servicePort:Number(form.servicePort),nginxBackendPort:form.serviceMode==='NGINX'?Number(form.nginxBackendPort):null,artifacts:form.artifacts.filter(a=>a.repositoryId&&a.artifactName).map((a,i)=>({...a,sortOrder:i}))});info.value='项目已创建：固定 database、current/config 目录和运行配置已准备。';showCreate.value=false;await load()}catch(e){error.value=err(e)}finally{saving.value=false}}
async function action(id,type){error.value='';try{if(type==='start')await startManagedProject(id);if(type==='stop')await stopManagedProject(id);if(type==='restart')await restartManagedProject(id);if(type==='preview')await previewManagedProject(id);await load()}catch(e){error.value=err(e)}}
onMounted(load)
</script>

<template><div class="page-stack restructure-page">
<PageHeader title="项目部署" description="Packages 制品下载解压到 current；FDP 管理 config、固定 database 与项目 Container，部署后人工启动。"><template #actions><button class="soft-button" @click="load"><RefreshCw :size="14"/>刷新</button><button class="primary-button" @click="showCreate=!showCreate"><Plus :size="14"/>新增项目</button></template></PageHeader>
<div v-if="error" class="error-banner">{{error}}</div><div v-if="info" class="success-banner">{{info}}</div>
<section v-if="showCreate" class="panel project-create-form"><div class="panel-head"><div><h2>新建项目</h2><p>一个项目一个 database；启动命令默认从 current/ 开始。</p></div></div>
<div class="form-grid restructure-form-grid"><label>项目名称 *<input v-model="form.projectName"/></label><label>Database *<input v-model="form.databaseName"/></label><label>Runtime Image *<select v-model="form.runtimeImage"><option v-for="i in images" :key="i" :value="i">{{i}}</option></select></label><label>工作目录<input v-model="form.workDirectory"/></label><label>服务模式<select v-model="form.serviceMode"><option>DIRECT</option><option>NGINX</option></select></label><label>服务端口<input v-model="form.servicePort" type="number"/></label><template v-if="form.serviceMode==='NGINX'"><label>静态目录<input v-model="form.nginxStaticDirectory"/></label><label>API 前缀<input v-model="form.nginxApiPrefix"/></label><label>后端端口<input v-model="form.nginxBackendPort" type="number"/></label></template></div>
<label style="display:flex;flex-direction:column;gap:7px;margin-top:12px">启动命令<textarea v-model="form.startCommand" rows="4"/></label><label style="display:flex;flex-direction:column;gap:7px;margin-top:12px">环境变量<textarea v-model="form.envContent" rows="5"/><small>DB_HOST / DB_PORT / DB_NAME / DB_USER / DB_PASSWORD 由 FDP 自动注入。</small></label>
<div class="panel-head" style="margin-top:16px"><div><h2>制品绑定</h2><p>按顺序解压，目录相对 current/。</p></div><button class="soft-button" @click="addArtifact">添加制品</button></div><div v-for="(a,i) in form.artifacts" :key="i" class="form-grid restructure-form-grid"><label>Repository ID<input v-model="a.repositoryId"/></label><label>Repository Name<input v-model="a.repositoryName"/></label><label>Artifact<input v-model="a.artifactName"/></label><label>解压目录<input v-model="a.targetDirectory"/></label></div><div style="display:flex;justify-content:flex-end;margin-top:12px"><button class="primary-button" :disabled="saving" @click="save"><Save :size="14"/>创建项目</button></div></section>
<section class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>项目</th><th>Database</th><th>Runtime</th><th>Container</th><th>版本</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="p in projects" :key="p.id"><td><strong>{{p.projectName}}</strong></td><td><code>{{p.databaseName}}</code></td><td><code>{{p.runtimeImage}}</code></td><td><code>{{p.containerName}}</code></td><td><code>{{p.deployedVersionSummary||'未部署'}}</code><small class="cell-note">运行：{{p.runningVersionSummary||'-'}} <b v-if="p.pendingRestart">待重启</b></small></td><td>{{p.deploymentStatus}}</td><td><div class="row-actions"><button class="soft-button" @click="action(p.id,'start')"><Play :size="13"/>启动</button><button class="soft-button" @click="action(p.id,'stop')"><Square :size="13"/>停止</button><button class="soft-button" @click="action(p.id,'restart')"><RotateCcw :size="13"/>重启</button><button class="soft-button" @click="action(p.id,'preview')">预览</button></div></td></tr></tbody></table></div><div v-if="!projects.length" class="empty-state">{{loading?'加载中…':'暂无项目'}}</div></section>
</div></template>
